# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: reverie
description: the quiet workstation

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "mkdir -p /nix && chmod 0755 /nix"

  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - atim/starship
        - agriffis/neovim-nightly
    install:
      packages:
        - fish
        - nix
        - nix-daemon
        - terra-release
        - starship
        - ghostty
        - zed
        - neovim
        - python3-neovim
        - tailscale
        - ripgrep
        - atuin
        - zoxide
        - lazygit
        - ibus-rime
        - librime-lua
        - https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
        - https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.4.7/Clash.Verge-2.4.7-1.x86_64.rpm
        - https://github.com/xpipe-io/xpipe/releases/latest/download/xpipe-installer-linux-x86_64.rpm
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - nvtop
        - htop

  - type: script
    scripts:
      - rime-ice.sh

  - type: systemd
    system:
      enabled:
        - nix-daemon.service

  - type: chezmoi
    repository: "https://github.com/AsterisMono/dotfiles"
    file-conflict-policy: replace

  - type: default-flatpaks
    configurations:
      - notify: true
        install:
          - com.google.Chrome
          - be.alexandervanhee.gradia
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.slack.Slack
          - com.tencent.wemeet
          - io.github.kolunmi.Bazaar
          - org.mozilla.Thunderbird
          - org.telegram.desktop
          - page.tesk.Refine
          - org.localsend.localsend_app

  - type: gnome-extensions
    install:
      - 615 # AppIndicator and KStatusNotifierItem Support
      - 3193 # Blur my Shell
      - 517 # Caffeine
      - 779 # Clipboard Indicator
      - 1160 # Dash to Panel
      - 6807 # System Monitor
      - 6099 # PaperWM

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: signing
